name: "Announcement Pull Request"
description: "A GitHub Action to add a comment on all open PRs"
inputs:
  message:
    description: "Custom comment to add to all open PRs"
    required: true
  token:
    description: "GitHub Token with repository access"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
