name: "Announcement Pull Request"
description: "A GitHub Action to add a comment on all open PRs"
inputs:
  message:
    description: "Custom comment to add to all open PRs"
    required: true
  token:
    description: "GitHub Token with repository access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add a comment to open PRs
      run: |
        # Fetch the current repository details from GitHub context
        OWNER="${{ github.repository_owner }}"
        REPO="${{ github.repository }}"
        MESSAGE="${{ inputs.message }}"
        TOKEN="${{ inputs.token }}"

        PRS=$(curl -s -H "Authorization: token $TOKEN" \
          "https://api.github.com/repos/$OWNER/$REPO/pulls?state=open")

        for PR in $(echo "$PRS" | jq -r '.[].number'); do
          echo "Adding comment to PR #$PR"
          curl -s -X POST -H "Authorization: token $TOKEN" \
            -d "{\"body\":\"$MESSAGE\"}" \
            "https://api.github.com/repos/$OWNER/$REPO/issues/$PR/comments"
        done
      shell: bash
