name: "Announcement Pull Request"
description: "A GitHub Action to add a comment on all open PRs"
inputs:
  message:
    description: "Custom comment to add to all open PRs"
    required: true
  token:
    description: "GitHub Token with repository access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add a comment to open PRs
      run: |
        # Fetch the current repository details from GitHub context
        OWNER_REPO="${{ github.repository }}"
        MESSAGE="${{ inputs.message }}"
        TOKEN="${{ inputs.token }}"

        PRS=$(curl -s -H "Authorization: Bearer $TOKEN" \
          "https://api.github.com/repos/$OWNER_REPO/issues")

        # Debug: Print the response to see the structure
        echo "Response from GitHub API:"
        echo "$PRS"
        echo "Owner: $OWNER"
        echo "Repo: $REPO"

        PR_COUNT=$(echo "$PRS" | jq length)
        if [ "$PR_COUNT" -gt 0 ]; then
          # Loop through each issue and check if it has the 'pull_request' key
          for PR in $(echo "$PRS" | jq -r '.[] | select(.pull_request != null) | .number'); do
            echo "Adding comment to PR #$PR"
            curl -s -X POST -H "Authorization: token $TOKEN" \
              -d "{\"body\":\"$MESSAGE\"}" \
              "https://api.github.com/repos/$OWNER_REPO/issues/$PR/comments"
          done
        else
          echo "No open PRs found."
        fi
      shell: bash
