name: "Announcement Pull Request"
description: "A GitHub Action to add a comment on all open PRs"
inputs:
  message:
    description: "Custom comment to add to all open PRs"
    required: true
  token:
    description: "GitHub Token with repository access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set execute permission for the script
      run: chmod +x ./script.sh

    - name: Run the announcement script
      run: ./script.sh "${{ inputs.message }}" "${{ inputs.token }}"
      shell: bash
